name: Polymarket Bot

on:
  workflow_dispatch:

  schedule:
    - cron: "*/15 * * * *"

permissions:
  contents: write

jobs:
  run-bot:

    runs-on: ubuntu-latest

    steps:

      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Ejecutar bot
        run: |
          python bot.py

      - name: Guardar memoria, historial, simulación y dashboard
        run: |

          git config user.name "PolymarketBot"
          git config user.email "bot@polymarket.local"

          git add precios_anteriores.json
          git add historial_movimientos.json
          git add simulacion.json
          git add dashboard.json

          git diff --cached --quiet || git commit -m "Actualizar datos del bot"

          git push
